//! Keeps a WireGuard interface in sync with the node's tunnel events.
//!
//! Always writes a wg-quick config (`<home>/wireguard/<iface>.conf`, mode
//! 0600). With `apply`, also pushes each change to a running interface via
//! `wg set`, which needs `CAP_NET_ADMIN` (or root).

use std::collections::BTreeMap;
use std::io::Write;
use std::net::{Ipv6Addr, SocketAddr};
use std::path::PathBuf;
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use threnody_core::tunnel::{WgKeys, base64, overlay_addr};
use threnody_core::{Identity, PublicIdentity};
use threnody_net::node::Secret;

struct Peer {
    wg_public: [u8; 32],
    endpoint: SocketAddr,
    overlay: Ipv6Addr,
    psk: Secret,
}

pub struct Tunnels {
    iface: String,
    port: u16,
    keys: WgKeys,
    me: Ipv6Addr,
    conf: PathBuf,
    apply: bool,
    peers: BTreeMap<[u8; 32], Peer>,
}

impl Tunnels {
    pub fn new(
        identity: &Identity,
        home: &std::path::Path,
        iface: String,
        port: u16,
        apply: bool,
    ) -> Result<Self> {
        if iface.is_empty()
            || iface.len() > 15
            || !iface
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "_-.".contains(c))
        {
            bail!("invalid interface name {iface:?}");
        }
        let conf = home.join("wireguard").join(format!("{iface}.conf"));
        let t = Self {
            iface,
            port,
            keys: WgKeys::derive(identity),
            me: overlay_addr(&identity.public()),
            conf,
            apply,
            peers: BTreeMap::new(),
        };
        t.write_conf()?;
        Ok(t)
    }

    pub fn conf_path(&self) -> &std::path::Path {
        &self.conf
    }

    pub fn overlay(&self) -> Ipv6Addr {
        self.me
    }

    pub fn summary(&self) -> String {
        format!(
            "wg {} udp/{} {} — {} peer(s){}",
            self.iface,
            self.port,
            self.me,
            self.peers.len(),
            if self.apply { ", applying live" } else { "" }
        )
    }

    pub fn up(
        &mut self,
        peer: &PublicIdentity,
        wg_public: [u8; 32],
        endpoint: SocketAddr,
        psk: Secret,
    ) -> Result<()> {
        let p = Peer {
            wg_public,
            endpoint,
            overlay: overlay_addr(peer),
            psk,
        };
        if self.apply {
            self.wg_set_peer(&p)?;
        }
        self.peers.insert(*peer.as_bytes(), p);
        self.write_conf()
    }

    pub fn down(&mut self, peer: &PublicIdentity, wg_public: Option<[u8; 32]>) -> Result<bool> {
        let removed = self.peers.remove(peer.as_bytes());
        let key = removed.as_ref().map(|p| p.wg_public).or(wg_public);
        if self.apply
            && let Some(k) = key
        {
            run_wg(&["set", &self.iface, "peer", &base64(&k), "remove"], None)?;
        }
        self.write_conf()?;
        Ok(removed.is_some())
    }

    fn wg_set_peer(&self, p: &Peer) -> Result<()> {
        let psk = zeroize::Zeroizing::new(base64(&p.psk.0[..]));
        run_wg(
            &[
                "set",
                &self.iface,
                "peer",
                &base64(&p.wg_public),
                "preshared-key",
                "/dev/stdin",
                "endpoint",
                &p.endpoint.to_string(),
                "allowed-ips",
                &format!("{}/128", p.overlay),
                "persistent-keepalive",
                "25",
            ],
            Some(psk.as_bytes()),
        )
    }

    /// Renders the wg-quick config. Contains the private key.
    pub fn render(&self) -> zeroize::Zeroizing<String> {
        use std::fmt::Write as _;
        // Written in place so secrets never pass through unzeroized temporaries.
        let mut s = zeroize::Zeroizing::new(String::with_capacity(1024));
        let _ = writeln!(
            s,
            "# Generated by threnody. Bring up with: sudo wg-quick up <this file>"
        );
        let _ = writeln!(s, "[Interface]");
        let _ = writeln!(s, "PrivateKey = {}", self.keys.secret_base64().as_str());
        let _ = writeln!(s, "ListenPort = {}", self.port);
        let _ = writeln!(s, "Address = {}/128", self.me);
        for p in self.peers.values() {
            let psk = zeroize::Zeroizing::new(base64(&p.psk.0[..]));
            let _ = writeln!(s, "\n[Peer]");
            let _ = writeln!(s, "PublicKey = {}", base64(&p.wg_public));
            let _ = writeln!(s, "PresharedKey = {}", psk.as_str());
            let _ = writeln!(s, "Endpoint = {}", p.endpoint);
            let _ = writeln!(s, "AllowedIPs = {}/128", p.overlay);
            let _ = writeln!(s, "PersistentKeepalive = 25");
        }
        s
    }

    fn write_conf(&self) -> Result<()> {
        let dir = self.conf.parent().expect("config path has a parent");
        std::fs::create_dir_all(dir)?;
        let tmp = self.conf.with_extension("tmp");
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create(true).truncate(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.mode(0o600);
        }
        let mut f = opts
            .open(&tmp)
            .with_context(|| format!("writing {}", tmp.display()))?;
        f.write_all(self.render().as_bytes())?;
        f.sync_all()?;
        std::fs::rename(&tmp, &self.conf)?;
        Ok(())
    }
}

fn run_wg(args: &[&str], stdin: Option<&[u8]>) -> Result<()> {
    let mut child = Command::new("wg")
        .args(args)
        .stdin(if stdin.is_some() {
            Stdio::piped()
        } else {
            Stdio::null()
        })
        .stderr(Stdio::piped())
        .spawn()
        .context("running wg (is wireguard-tools installed?)")?;
    if let Some(data) = stdin {
        child.stdin.take().expect("piped stdin").write_all(data)?;
    }
    let out = child.wait_with_output()?;
    if !out.status.success() {
        bail!(
            "wg {}: {}",
            args[..2].join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use zeroize::Zeroizing;

    #[test]
    fn config_tracks_peers_and_parses_with_wg_quick() {
        let dir = tempfile::tempdir().unwrap();
        let me = Identity::from_seed(&[1; 32]);
        let peer = Identity::from_seed(&[2; 32]).public();
        let mut t = Tunnels::new(&me, dir.path(), "thr0".into(), 51820, false).unwrap();
        t.up(
            &peer,
            [9; 32],
            "192.0.2.1:51820".parse().unwrap(),
            Secret(Zeroizing::new([5; 32])),
        )
        .unwrap();
        let conf = std::fs::read_to_string(t.conf_path()).unwrap();
        assert!(conf.contains(&format!("AllowedIPs = {}/128", overlay_addr(&peer))));
        assert!(conf.contains(&format!("PresharedKey = {}", base64(&[5; 32]))));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(t.conf_path())
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(mode & 0o777, 0o600);
        }
        assert!(t.down(&peer, None).unwrap());
        assert!(
            !std::fs::read_to_string(t.conf_path())
                .unwrap()
                .contains("[Peer]")
        );
        assert!(Tunnels::new(&me, dir.path(), "bad name; rm".into(), 1, false).is_err());
    }
}
